<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    // database-specific stuff
    'vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectorInterface.php',
    'vendor/laravel/framework/src/Illuminate/Database/Connection.php',
    'vendor/laravel/framework/src/Illuminate/Database/ConnectionInterface.php',
    'vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php',
    'vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php',
    'vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php',
    'vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php',
    'vendor/laravel/framework/src/Illuminate/Database/Grammar.php',
    'vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php',
    'vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php',
    'vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php',
    'vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php',
    'vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php',

    // eloquent and fluent stuff
    'vendor/laravel/framework/src/Illuminate/Support/Collection.php',
    'vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php',

    // controller-specific stuff
    'vendor/laravel/framework/src/Illuminate/Routing/ControllerServiceProvider.php',
    'vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php',
    'vendor/laravel/framework/src/Illuminate/Routing/Controllers/Inspector.php',
    'vendor/laravel/framework/src/Illuminate/Routing/Controllers/Filter.php',
    'vendor/laravel/framework/src/Illuminate/Routing/Controllers/Before.php',
    'vendor/laravel/framework/src/Illuminate/Routing/Controllers/After.php',
    'vendor/laravel/framework/src/Illuminate/Routing/Controllers/FilterParser.php',

    // URL generator
    'vendor/symfony/routing/Symfony/Component/Routing/Generator/ConfigurableRequirementsInterface.php',
    'vendor/symfony/routing/Symfony/Component/Routing/Generator/UrlGeneratorInterface.php',
    'vendor/symfony/routing/Symfony/Component/Routing/Generator/UrlGenerator.php',
    'vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php',

);
